#!/bin/bash
BATT=$( acpi -b | sed 's/.*[charging|unknown], \([0-9]*\)%.*/\1/gi' )
STATUS=$( acpi -b | sed 's/.*: \([a-zA-Z]*\),.*/\1/gi' )
if [ $BATT -le 15 ]  && [ $STATUS == "Discharging" ]; then
    amixer sset Master unmute
    abeep && sleep 0.05
    abeep && sleep 0.05
    abeep && sleep 0.05
fi
