#!/bin/sh

# Loop through all attached batteries.
for battery in /sys/class/power_supply/BAT?
do
	# Get its remaining capacity and charge status.
	capacity=$(cat "$battery"/capacity)
	status=$(sed "s/Discharging/⚡/;s/Not charging/❗/;s/Charging/♻/;s/Unknown/idk/;s/Full//" "$battery"/status)

	# If it is discharging and 25% or less, 
	 
	[ "$capacity" -le 29 ] && [ "$status" = "⚡" ] && warn="!!!"
		
	printf "%s%s%s%%\n" "$status" "$capacity" "$warn"
	unset warn
done




