#!/bin/sh
export SEP1=" | "
export SEP2=""
export IDENTIFIER="unicode"
while [ true ]
do
       	xsetroot -name "$(netup)| $(volctl)| $(batt) $(weather)| $(date +%a\-%m\-%-e\-%Y\-%-I:%M%P)"
   	battwarn
	sleep 1m
done 
