#!/bin/sh
LOCATION=ewr
OUTPUT="$(curl -s wttr.in/?format=1)"  

#if [ $(echo $OUTPUT|awk '{print $1}') == "Unknown" ]; then printf "hey";fi

if [ "$IDENTIFIER" = "unicode" ]; then
  printf "%s" "$OUTPUT"
else
  printf "%s" "$OUTPUT"|grep -o "[+-][0-9][0-9]" 
fi

